repos:
-   repo: local
    hooks:
      - id: isort
        name: isort
        language: system
        types: [ python ]
        entry: isort  --settigns-file pyproject.toml src/
        exclude: ^migrations/

      - id: black
        name: black
        language: system
        types: [ python ]
        entry: black --config pyproject.toml src/
        exclude: ^migrations/


      - id: flake8
        name: flake8
        language: system
        types: [ python ]
        entry: flake8 --config .flake8 src/
        exclude: ^migrations/
