repos:
-   repo: local
    hooks:
      - id: isort
        name: isort
        language: python
        types: [ python ]
        entry: isort src/

      - id: black
        name: black
        language: python
        types: [ python ]
        entry: black src/


      - id: flake8
        name: flake8
        language: python
        types: [ python ]
        entry: flake8 src/
